# Nome do serviço (importante para o relatório e para o Service Discovery futuro)
spring.application.name=auth-service
# Porta onde este serviço vai correr (para não chocar com o monólito na 8080)
server.port=8081
# Ligação à base de dados (Postgres que criámos no Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/xcommerce
spring.datasource.username=postgres
spring.datasource.password=postgres
# Hibernate (gera as tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
