services:
  postgres-db:
    image: postgres:15
    container_name: xcommerce-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=xcommerce
    ports:
      - "5432:5432"

  redis-cache:
    image: redis:alpine
    container_name: xcommerce-redis
    ports:
      - "6379:6379"