spring.application.name=inventory-service
server.port=8085

spring.datasource.url=jdbc:postgresql://db:5432/xcommerce_inventory
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect