# Nome do serviço
spring.application.name=cart-service

# Porta diferente dos outros (8081 Auth, 8082 Catalog)
server.port=8083

# Ligação à Base de Dados (Cria uma nova BD chamada xcommerce_cart no Docker se puderes)
spring.datasource.url=jdbc:postgresql://localhost:5432/xcommerce_cart
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate cria as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Força o Hibernate a usar o padrão de nomes do Spring (snake_case)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# Mostra o erro real na consola do VS Code
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# include error details in HTTP responses for troubleshooting
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always