spring.application.name=identity-service
server.port=8081

# PostgreSQL — instância dedicada
spring.datasource.url=jdbc:postgresql://db-identity:5432/xcommerce_identity
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Flyway desativado (delegado a ddl-auto)
spring.flyway.enabled=false

# JWT — token artesanal (HS256)
jwt.secret=xcommerce-secret-key-please-rotate-in-production

# Spring Cloud Config desativado
spring.cloud.config.enabled=false
spring.cloud.config.fail-fast=false

# Kafka — publica user-events (login)
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.consumer.group-id=identity-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Management & Observabilidade
management.endpoints.web.exposure.include=health,info,metrics,prometheus,tracing
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.endpoint.prometheus.access=UNRESTRICTED
management.otlp.metrics.export.enabled=false
management.otlp.tracing.endpoint=http://jaeger:4318/v1/traces
management.tracing.sampling.probability=1.0

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

server.forward-headers-strategy=framework

# Logging
logging.level.root=INFO
logging.level.com.xcommerce=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [traceId=%X{traceId:-},spanId=%X{spanId:-}] - %msg%n
