spring.application.name=cart-service
server.port=8083

# Base de Dados
spring.datasource.url=jdbc:postgresql://db:5432/xcommerce_cart
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Estratégia de Naming e Debug
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Erros
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always

# Swagger & Gateway Config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.forward-headers-strategy=framework

# Kafka Config
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.consumer.group-id=cart-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Prometheus, Tracing & Jaeger
management.endpoints.web.exposure.include=health,info,prometheus,tracing
management.endpoint.prometheus.access=UNRESTRICTED
management.otlp.metrics.export.enabled=false
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://jaeger:4318/v1/traces
