server.port=9000
spring.application.name=api-gateway

# Gateway debug logging
logging.level.org.springframework.cloud.gateway=INFO

# Compatibilidade com Spring Boot 4
spring.main.allow-bean-definition-overriding=true
management.endpoint.gateway.access=UNRESTRICTED

# Prometheus & Tracing
management.endpoints.web.exposure.include=health,info,gateway,prometheus,tracing
management.endpoint.prometheus.access=UNRESTRICTED
management.otlp.metrics.export.enabled=false
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://jaeger:4318/v1/traces
spring.cloud.gateway.httpclient.connect-timeout=2000
spring.cloud.gateway.httpclient.response-timeout=5s

# OAuth2 Resource Server (Keycloak Integration)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/xcommerce
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/xcommerce/protocol/openid-connect/certs

# Spring Cloud Config Client
spring.config.import=configserver:http://config-server:8888
spring.cloud.config.fail-fast=false
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.max-attempts=6

resilience4j.timelimiter.instances.auth-gateway-cb.timeout-duration=5s
resilience4j.timelimiter.instances.catalog-gateway-cb.timeout-duration=5s
resilience4j.timelimiter.instances.catalog-brand-gateway-cb.timeout-duration=5s
resilience4j.timelimiter.instances.catalog-category-gateway-cb.timeout-duration=5s
resilience4j.timelimiter.instances.cart-gateway-cb.timeout-duration=5s
resilience4j.timelimiter.instances.order-gateway-cb.timeout-duration=5s
resilience4j.timelimiter.instances.inventory-gateway-cb.timeout-duration=5s
resilience4j.timelimiter.instances.user-gateway-cb.timeout-duration=5s
resilience4j.timelimiter.instances.payment-gateway-cb.timeout-duration=5s
resilience4j.timelimiter.instances.notification-gateway-cb.timeout-duration=5s

# --- SWAGGER/OPENAPI AGGREGATION ---
springdoc.swagger-ui.urls[0].name=Catalog Service
springdoc.swagger-ui.urls[0].url=/docs/catalog
springdoc.swagger-ui.urls[1].name=Auth Service
springdoc.swagger-ui.urls[1].url=/docs/auth
springdoc.swagger-ui.urls[2].name=Cart Service
springdoc.swagger-ui.urls[2].url=/docs/cart
springdoc.swagger-ui.urls[3].name=Order Service
springdoc.swagger-ui.urls[3].url=/docs/order
springdoc.swagger-ui.urls[4].name=Inventory Service
springdoc.swagger-ui.urls[4].url=/docs/inventory
springdoc.swagger-ui.urls[5].name=User Service
springdoc.swagger-ui.urls[5].url=/docs/users
springdoc.swagger-ui.urls[6].name=Payment Service
springdoc.swagger-ui.urls[6].url=/docs/payments
springdoc.swagger-ui.urls[7].name=Notification Service
springdoc.swagger-ui.urls[7].url=/docs/notifications
