server.port=8088
spring.application.name=notification-service

logging.level.com.xcommerce.notification_service=DEBUG

# Faz com que o microserviço responda explicitamente neste caminho
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html