server.port=8087
spring.application.name=payment-service

logging.level.org.springframework.web=INFO

# Faz com que o microserviço responda explicitamente neste caminho
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html