spring.application.name=payment-service
server.port=8087

# Logging
logging.level.org.springframework.web=INFO

# Swagger & Gateway Config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.forward-headers-strategy=framework

# Kafka Config
spring.kafka.bootstrap-servers=kafka:29092

# Configuração do Consumidor
spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Configuração do Produtor
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Prometheus, Tracing & Jaeger
management.endpoints.web.exposure.include=health,info,prometheus,tracing
management.endpoint.prometheus.access=UNRESTRICTED
management.otlp.metrics.export.enabled=false
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://jaeger:4318/v1/traces
