global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'xcommerce-microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 
          - 'gateway:9000'
          - 'auth-service:8081'
          - 'catalog-service:8082'
          - 'cart-service:8083'
          - 'order-service:8084'
          - 'inventory-service:8085'
          - 'user-service:8086'
          - 'payment-service:8087'
          - 'notification-service:8088'