spring.application.name=order-service
server.port=8084

# Base de Dados
spring.datasource.url=jdbc:postgresql://db:5432/xcommerce_orders
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Swagger & Gateway Config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.forward-headers-strategy=framework

# Kafka Config
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Remote Call Timeouts
spring.cloud.openfeign.client.config.default.connectTimeout=2000
spring.cloud.openfeign.client.config.default.readTimeout=4000

# Spring Cloud Config Disable
spring.cloud.config.import-check.enabled=false

# Prometheus, Tracing & Jaeger
management.endpoints.web.exposure.include=health,info,prometheus,tracing
management.endpoint.prometheus.access=UNRESTRICTED
management.otlp.metrics.export.enabled=false
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://jaeger:4318/v1/traces
