spring.application.name=order-service
server.port=8084

# Base de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/xcommerce_orders
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true